apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alert-manager-pdb
  namespace: costwatch
  labels:
    app: alert-manager
    component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: alert-manager
  unhealthyPodEvictionPolicy: AlwaysAllow
